# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  python-test:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -p probs

      - run:
          name: run lint
          command: |
            . venv/bin/activate
            flake8 --exclude venv

  java-test:
    docker:
      - image: circleci/openjdk:9-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install junit
          command: |
            sudo apt-get install junit4 -y

      - run:
          name: download cpsuite
          command: |
            cd java
            sudo mkdir lib
            sudo wget -O lib/cpsuite-1.2.6.jar https://www.dropbox.com/s/fvi9v0t287vgsnq/cpsuite-1.2.6.jar\?dl\=1

      - run:
          name: compile
          command: |
            cd java
            sudo javac -cp src src/probs/**/*.java
            sudo javac -cp .:/usr/share/java/junit4.jar:lib/cpsuite-1.2.6.jar:src test/probs/**/*.java
            sudo javac -cp .:/usr/share/java/junit4.jar:lib/cpsuite-1.2.6.jar:src test/probs/*.java

      - run:
          name: run tests
          command: |
            cd java
            sudo java -cp .:/usr/share/java/junit4.jar:lib/cpsuite-1.2.6.jar:test:src probs.RunAllSuite
            sudo java -cp .:/usr/share/java/junit4.jar:java/test:java/src org.junit.runner.JUnitCore probs.prob09_divisor.DivisorTest

workflows:
  version: 2
  tests:
    jobs:
      - java-test
      - python-test
