# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  python-test:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -p probs

      - run:
          name: run lint
          command: |
            . venv/bin/activate
            flake8 --exclude venv

  java-test:
    docker:
      - image: circleci/openjdk:8

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: maven-{{ checksum "java/pom.xml" }}
          key: maven

      - run:
          name: install maven
          command: |
            sudo apt-get install maven -y

      - run:
          name: compile
          command: |
            cd java
            mvn compile

      - save_cache:
          key: maven-{{ checksum "java/pom.xml" }}

          paths:
          - ~/.m2

      - run:
          name: run tests
          command: |
            cd java
            mvn test

workflows:
  version: 2
  tests:
    jobs:
      - java-test
      - python-test
